# Generated by Django 4.2 on 2024-05-14 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("planitapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialtoken",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="socialtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
